
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_components/home/header/Nav";
import GlobalContextprovider from "./context/GobalContext";
// import Footer from "./_components/home/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <GlobalContextprovider>
        <Nav />
       
        {children}
        </GlobalContextprovider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
